config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get 'articles/get_archived_posts', to: "articles#get_archived_posts"
  get 'home/about'
  get 'home/index'

  resources :articles do
    get :change_to_public, member: true
    resources :comments
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end

    def archived_count
      where(status: 'archived').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:update, :edit, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @articles = Article.all
  end

  def get_archived_posts
    @articles = Article.where(user_id: current_user.id)
    @archived_article_count = @articles.where(status: 'archived')
    puts @archived_article_count, 'hi'
  end

  def change_to_public
    @article = Article.find(params[:article_id])
    @article.status = "public"
    if @article.save
      redirect_to articles_get_archived_posts_path

    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    #if @article.save
    #  redirect_to @article
    #else
    #  render :new, status: :unprocessable_entity
    #end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    #if @article.update(article_params)
    #  redirect_to @article
    #else
    #  render :new, status: :uunprocessable_entity
    #end
  end

  def destroy
    @article.destroy

    #redirect_to root_path, status: :see_other
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Article was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :user_id)
    end
    def find_article
      @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>

    <%= form.label :title %><br>
    <%= form.text_field :title, placeholder: "Enter the title..." %>
    <% article.errors.full_messages_for(:title).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, placeholder:"Enter the content..." %>
    <%  article.errors.full_messages_for(:body).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :article_user_id, value: current_user.id, type: :hidden %>
    <%  article.errors.full_messages_for(:body).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Article::VALID_STATUSES, selected: article.status %>
  </div>
  <br>

  <div >
    <%= form.submit class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "Edit Article") %>
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/get_archived_posts.html.erb
<% provide(:title, "All Archived Articles") %>
<h1>Archived Articles</h1>

<% if @archived_article_count == 0 or @archived_article_count == [] %>
  <h2>You have 0 Archived Posts</h2>
<% else %>
  <% @articles.each do |article| %>
  	<% if article.archived? %>
  		<h3"><%= link_to article.title, article %> 
  		<%= link_to "Change To Public", article_change_to_public_path(article.id), class:"btn btn-outline-dark btn-sm" %>
  		</h3>
  	</div>
   		<br>
  	<% end %>
  <% end %>
<% end %>
<br> <br>

app/views/articles/index.html.erb
<% provide(:title, "All Articles") %>
<h1>Articles</h1>
<h2>The Blog has <%= Article.public_count %> articles and counting!</h2>
<ul>
  <% @articles.each do |article| %>
  <% unless article.archived? %>
    <li>
      <%= link_to article.title, article %> by 
      <%= article.user.email %>
    </li>
    <% end %>
  <% end %>
</ul>

<% if user_signed_in? %>
	<%= link_to "Show Archived Articles", articles_get_archived_posts_path, class: "btn btn-dark" %>
<% end %>

app/views/articles/new.html.erb
<% provide(:title, "New Article") %>
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<div class="card">
  <div class="card-header ">
   <h1><%= @article.title %> </h1>
  </div>
  <div class="card-body">
  	<p>
    <%= @article.body %>
	</p>
  </div>
</div>


<!-- <h1><%= @article.title %></h1> -->
<!-- <p><%= @article.body %></p> -->
<br>

<h2>Comments</h2>
<br>
<%= render @article.comments%>


<h2>Add a comment: </h2>
<%= render 'comments/form' %>


<% if user_signed_in? and current_user.id == @article.user_id %>
<div class="d-flex flex-rows gap-2" >
	<%= button_to "Edit this Article", edit_article_path(@article), method: :get, class:"btn btn-outline-dark mr-2" %>
	
	<%= button_to "Delete this Article", article_path(@article), method: :delete, class: "btn btn-outline-danger mr-2",data: {confirm: "Are you sure you want to reset the indexes?" } %>
</div>
<br>
<% end %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <% if  user_signed_in? and comment.commenter == current_user.email || Article.find(comment.article_id).user_id == current_user.id %> 
    <p>
        <%= button_to "Delete this comment", [comment.article, comment], method: :delete, class:"btn btn-danger" %>
    </p>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
    <%= form_with model: [ @article, @article.comments.build ] do |form| %>
        <p>
            <%= form.text_field :commenter, value: current_user.email,type: :hidden  %>
        </p>
        <p>
            <%= form.label :body, "Comment" %> <br>
            <%= form.text_area :body, placeholder: "Type your comment..." %>
        </p>

        <p>
            <%= form.label :status %><br>
            <%= form.select :status, Article::VALID_STATUSES, selected: 'public', class: "bg-dark" %>
            
        </p>

        <p>
        <div>
            <%= form.submit class: "btn btn-dark"%>
        </div>
        </p>
    <% end %>
<% else %>
    <%= form_with model: [ @article, @article.comments.build ] do |form| %>
        <p>
            <%= form.text_field :commenter, value: "xyz",type: :hidden  %>
        </p>
        <p>
            <%= form.label :body, "Comment" %> <br>
            <%= form.text_area :body, placeholder: "Type your comment..." %>
        </p>

        <p>
            <%= form.label :status %><br>
            <%= form.select :status, Article::VALID_STATUSES, selected: 'public' %>
        </p>

        <p>
            <%= form.submit class: "btn btn-dark" %>
        </p>
    <% end %>

<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!--<div class="container-fluid">-->
    <%= link_to "Blog App", home_index_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'All Articles', articles_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About me', home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to 'New Article', new_article_path, class:"nav-link" %>
          </li>
          

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, class:"nav-link " %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
          </li>     
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<% provide(:title, "About me") %>
<h1>About me... </h1>
<p>My Name is Shubharthak Sangharsha, the developer of this app</p>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<h1>Welcome to Article App by Shubharthak</h1> <br>
<p>If you hadn't sign-up or sign-in. Please do it for creating your blog post</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title><%=yield(:title) %></title>
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
      <br>
        <% if notice %>
          <%= render "layouts/alerts" %>
        <% end %>

        <%= yield %>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>